name: Telegram notifications on events
on:
  pull_request:
    types: [opened]
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Get branch name on a pull request
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - uses: actions/checkout@master
    - name: send custom message on PR
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message:  "PR created from branch [${{ env.BRANCH_NAME }}] to the [yearn-fiance] web repo."
